/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.videoco.eecs3311.project;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.UUID;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author kvjha
 */
public class NormalUserScreen extends javax.swing.JFrame {
    NormalUser user;
    /**
     * Creates new form NormalUserScreen
     */
    public NormalUserScreen(NormalUser user) {
        this.user=user;
        initComponents();
        WelcomeLabel.setText("Welcome " + user.getUsername());
        WelcomeText.setText("Choose an option on the left to view various functionalities");
        CardLayout card=(CardLayout)Parent.getLayout();
        card.show(Parent, "WelcomePanel");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        ViewOrdersButton = new javax.swing.JButton();
        ViewAndEditInfoButton = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        VandEInfoPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        WelcomeText = new javax.swing.JLabel();
        ViewOrdersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        CreateOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NormalUserScreen");
        setMinimumSize(new java.awt.Dimension(750, 750));

        jPanel2.setBackground(new java.awt.Color(144, 233, 144));
        jPanel2.setLayout(null);

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(HomeButton);
        HomeButton.setBounds(10, 70, 170, 30);

        SearchButton.setText("Search Movies");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton);
        SearchButton.setBounds(10, 110, 170, 29);

        ViewOrdersButton.setText("View Orders");
        ViewOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrdersButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ViewOrdersButton);
        ViewOrdersButton.setBounds(10, 150, 170, 30);

        ViewAndEditInfoButton.setText("View/Edit Information");
        jPanel2.add(ViewAndEditInfoButton);
        ViewAndEditInfoButton.setBounds(10, 200, 170, 29);

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        SearchPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Search");

        SearchBar.setFont(new java.awt.Font("Monaco", 2, 14)); // NOI18N
        SearchBar.setText("Enter UUID/Genre/Movie Name");
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resultsTable);

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(SearchPanel, "SearchPanel");

        javax.swing.GroupLayout VandEInfoPanelLayout = new javax.swing.GroupLayout(VandEInfoPanel);
        VandEInfoPanel.setLayout(VandEInfoPanelLayout);
        VandEInfoPanelLayout.setHorizontalGroup(
            VandEInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        VandEInfoPanelLayout.setVerticalGroup(
            VandEInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        Parent.add(VandEInfoPanel, "card6");

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 255));

        WelcomeLabel.setText("jLabel1");

        WelcomeText.setText("jLabel1");

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(WelcomeLabel))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(WelcomeText)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(WelcomeLabel)
                .addGap(144, 144, 144)
                .addComponent(WelcomeText)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        Parent.add(WelcomePanel, "WelcomePanel");

        ViewOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Orders");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ordersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ordersTable);

        CreateOrder.setText("CreateOrder");
        CreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewOrdersPanelLayout = new javax.swing.GroupLayout(ViewOrdersPanel);
        ViewOrdersPanel.setLayout(ViewOrdersPanelLayout);
        ViewOrdersPanelLayout.setHorizontalGroup(
            ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                    .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                        .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel2))
                            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(CreateOrder)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ViewOrdersPanelLayout.setVerticalGroup(
            ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateOrder)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Parent.add(ViewOrdersPanel, "ViewOrdersPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card=(CardLayout)Parent.getLayout();
        card.show(Parent, "SearchPanel");
        String[] col={"Name","ID","Stock","Price","Genre"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);        
        resultsTable.setModel(tableModel);

    }//GEN-LAST:event_SearchButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card=(CardLayout)Parent.getLayout();
        card.show(Parent, "WelcomePanel");
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String s= SearchBar.getText();
        ArrayList<Movie> movies;
        if(s.equals("")){
            movies=user.search();            
        }else{
           movies=user.search(s);
        }
        String[] col={"Name","ID","Stock","Price","Genre"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for(Movie movie: movies){
            
            String[] row={movie.getTitle(), movie.getId().toString(), String.valueOf(movie.getStock()), String.valueOf(movie.getPrice()), movie.getMovieInfo().getGenre().toString()};
            
            tableModel.addRow(row);
        }
        resultsTable.setModel(tableModel);
        resultsTable.getColumnModel().getColumn(0).setMinWidth(100);
        resultsTable.getColumnModel().getColumn(1).setMinWidth(150);
        resultsTable.getColumnModel().getColumn(2).setPreferredWidth(25);
        resultsTable.getColumnModel().getColumn(3).setPreferredWidth(25);
        resultsTable.getColumnModel().getColumn(4).setPreferredWidth(75);

        


    }//GEN-LAST:event_searchActionPerformed

    private void resultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsTableMouseClicked
        // TODO add your handling code here:
        int index= resultsTable.getSelectedRow();
        TableModel model= resultsTable.getModel();
        String id= model.getValueAt(index,1).toString();
        UserMovieFrame frame= new UserMovieFrame();
        SystemV sys= SystemV.getInstance();
        frame.initMovie(sys.getMovie(UUID.fromString(id)));
        frame.initUser(this.user);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_resultsTableMouseClicked
    private void updateOrdersTable(){
        String [] col= {"OrderID","OrderStatus","Price","ShippingAddress","OrderDate"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for(UserOrder order: user.getOrders()){
            String[] row={order.getOrderID().toString(),order.getOrderStatus().toString(), String.valueOf(order.getOrderPrice()),order.getShippingAddress(),order.getOrderDate().toString()};
            tableModel.addRow(row);
        }
        ordersTable.setModel(tableModel);
        
    }
    private void ViewOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrdersButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card=(CardLayout)Parent.getLayout();
        card.show(Parent, "ViewOrdersPanel");
        String [] col= {"OrderID","OrderStatus","Price","ShippingAddress","OrderDate"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for(UserOrder order: user.getOrders()){
            String[] row={order.getOrderID().toString(),order.getOrderStatus().toString(), String.valueOf(order.getOrderPrice()),order.getShippingAddress(),order.getOrderDate().toString()};
            tableModel.addRow(row);
        }
        ordersTable.setModel(tableModel);
        

        
    }//GEN-LAST:event_ViewOrdersButtonActionPerformed

    private void ordersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersTableMouseClicked
        // TODO add your handling code here:
        int index= ordersTable.getSelectedRow();
        TableModel model= ordersTable.getModel();
        String id= model.getValueAt(index,0).toString();
        UserOrderView frame= new UserOrderView();
        SystemV sys= SystemV.getInstance();
        frame.setVisible(true);
        UserOrder o=null;
        for(UserOrder order: user.getOrders()){
             if(order.getOrderID().toString().equals(id)){
                o=order;
                break;
            }
        }
        frame.initOrder(o);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        frame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                   updateOrdersTable();
            }
        });


    }//GEN-LAST:event_ordersTableMouseClicked

    private void CreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrderActionPerformed
        // TODO add your handling code here:
        UserOrder order= new UserOrder(UUID.randomUUID(),this.user);
        this.user.addOrder(order);
        updateOrdersTable();
        UserOrderView frame= new UserOrderView();
        order.setPayWithPoints(false);
        frame.initOrder(order);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                   updateOrdersTable();
            }
        });
        
        
    }//GEN-LAST:event_CreateOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NormalUserScreen(user).setVisible(true);
//            }
//        });
           
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateOrder;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel Parent;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JPanel VandEInfoPanel;
    private javax.swing.JButton ViewAndEditInfoButton;
    private javax.swing.JButton ViewOrdersButton;
    private javax.swing.JPanel ViewOrdersPanel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ordersTable;
    private javax.swing.JTable resultsTable;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
